<?php
function myhooks_civicrm_pageRun(&$page) {
    $pageName = $page->getVar('_name');
    if($pageName == 'CRM_Member_Page_Tab'){
        $membershipId = $page->getVar('_id');
        //More secure way to protect from SQL Injections
        $dao = CRM_Utils_SQL_Select::from('civicrm_membership_log cml')
            ->select('cml.*, cms.name AS membership_status_name, cmt.name AS membership_type_name')
            ->join('cms', 'INNER JOIN civicrm_membership_status cms ON cms.id = cml.status_id')
            ->join('cmt', 'INNER JOIN civicrm_membership_type cmt ON cmt.id = cml.membership_type_id')
            ->where('cml.membership_id = @membershipId')
            ->param(array(
                'membershipId' => $membershipId
            ));
        $dao = CRM_Core_DAO::executeQuery( $dao->toSQL() )->getDatabaseResult();
        $page->assign('membershipPeriodInfo', $dao->result);
    }
}